export const htmlToConvert = `<div class="post-category entry-category">Messaggio di Daisaku Ikeda</div>
<h1 class="entry-title">Continuiamo a diffondere dialoghi per la pace</h1>
<div class="post-teaser entry-teaser">per i corsi estivi della SGI in Europa</div>
<img class="post-img" src="" />
<div class="post-content entry-content">
  <style type="text/css"> img.wp-smiley, img.emoji {  display: inline !important;  border: none !important;  box-shadow: none !important;  height: 1em !important;  width: 1em !important;  margin: 0 .07em !important;  vertical-align: -0.1em !important;  background: none 
!important;  padding: 0 !important; } </style>  <link rel='stylesheet' id='mci-footnotes-jquery-tooltips-pagelayout-none-css'  href='https://ilnuovorinascimento.org/wp-content/plugins/footnotes/css/footnotes-jqttbrpl0.min.css' type='text/css' media='all' /> <link rel='stylesheet' id='custom_style_css-css'  href='https://ilnuovorinascimento.org/wp-content/plugins/divi-overlays/assets/css/style.css' type='text/css' media='all' /> <script type='text/javascript' src='https://ilnuovorinascimento.org/wp-includes/js/jquery/jquery.min.js' id='jquery-core-js'></script> <script type='text/javascript' src='https://ilnuovorinascimento.org/wp-includes/js/jquery/jquery-migrate.min.js' id='jquery-migrate-js'></script> <script type='text/javascript' src='https://ilnuovorinascimento.org/wp-content/plugins/footnotes/js/jquery.tools.min.js' id='mci-footnotes-jquery-tools-js'></script> <script type='text/javascript' src='https://ilnuovorinascimento.org/wp-includes/js/jquery/ui/core.min.js' id='jquery-ui-core-js'></script> <script type='text/javascript' src='https://ilnuovorinascimento.org/wp-includes/js/jquery/ui/tooltip.min.js' id='jquery-ui-tooltip-js'></script> <script type='text/javascript' src='https://ilnuovorinascimento.org/wp-content/plugins/divi-overlays/assets/js/snap.svg-min.js' id='snap_svg_js-js'></script> <script type='text/javascript' src='https://ilnuovorinascimento.org/wp-content/plugins/divi-overlays/assets/js/modernizr.custom.js' id='modernizr_js-js'></script> <style>/**                         * Created by Stefan Herndler.
* User: Stefan                         * Date: 15.05.14                         * Time: 16:21                         * Version: 1.0.7                         * Since: 1.0                         */                                          /* Footnotes */
.footnote_tag_styling, .footnote_tag_styling:hover {                         text-decoration: none;                         font-weight: normal;                     }                                          .footnote_tag_styling_1 {                         color: #2bb975;        
}                                          .footnote_tag_styling_2 {                         color: #545f5a;
}                                          /* superscript */                     .footnote_plugin_tooltip_text {                         vertical-align: top !important;                         position: relative !important;                         top: -0.1em !important;
cursor: pointer;                     }                                          /* reference container label */
.footnote_container_prepare {                         display: block !important;                         padding-top: 24px !important;      
 }                                          .footnote_container_prepare > p {                         line-height: 1.3 !important;                         margin-top: 1em !important;                         margin-bottom: 0.25em !important;                         padding: 0 !important;                         font-weight: normal !important;                         overflow: hidden !important;
border-bottom: 1px solid #aaaaaa !important;                         display: block !important;                         -webkit-margin-before: 0.83em !important;                         -webkit-margin-after: 0.83em !important;                         -webkit-margin-start: 0px !important;                         -webkit-margin-end: 0px !important;                         text-align: left !important;
vertical-align: middle;                     }                                          .footnote_container_prepare > p > span:first-child {                         padding-left: 20px !important;                         text-align: left !important;                         cursor: pointer;                         font-size: 1.5em !important;                     }                                          /* reference container */                     .footnote-reference-container {                         width: 100%;                         border: none;  
     }                                          /* index */                     .footnote_plugin_index {
vertical-align: top;                         white-space: nowrap;                         padding-right: 5px;                         text-align: left;                         border:none !important;                         max-width:10% !important;                     }
                /* arrow */                     .footnote_plugin_link {                         vertical-align: top;
white-space: nowrap;                         padding-right: 5px;                         text-align: left;
cursor: pointer;                     }                                          /* text */                     .footnote_plugin_text {      
     vertical-align: top;                         width: 99%;                         text-align: left;                     }   
.footnote_plugin_tooltip_text {font-size: 0.8em !important; font-weight: bold !important; top: -0.025em !important;}            .footnote_tooltip { display: none; padding: 12px; font-size: 13px; color: #a50000; background-color: #ffffff; border-width: 1px;       border-style: solid; border-color: #a50000; border-radius: 3px; -webkit-box-shadow: 2px 2px 11px #666666; -moz-box-shadow: 2px 2px 11px #666666; box-shadow: 2px 2px 11px #666666;}           </style><div class="soundcloud-player"><iframe src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1305687034&amp;color=%233e8498&amp;inverse=false&amp;auto_play=false&amp;show_user=false&amp;show_reposts=false&amp;show_teaser=false" width="100%" height="20" frameborder="no" scrolling="no"></iframe></div><br><div class='one_fourth et_column_last'>           </div><div class='clear'></div>Ai miei cari amici della SGI in Europa,<br>grazie infinite per il vostro impegno nel realizzare questo corso estivo, una tradizione della SGI.<br>Nichiren Daishonin è senza dubbio a conoscenza delle nobili azioni che state compiendo mentre vi impegnate, in questi tempi sempre più difficili, a realizzare l’ideale di <em>kosen-rufu</em>, che equivale alla pace nel mondo.<br>La “ricompensa visibile” che deriva da queste azioni di “virtù invisibile” si manifesterà immancabilmente.<br>Nichiren Daishonin afferma: «Per coloro che hanno una fede profonda è come se la notte fosse illuminata dalla luna piena» (<em>L’essenza del capitolo “Re della Medicina”</em>, RSND, 1, 81). La Legge mistica è una profonda filosofia di speranza e saggezza che disperde ogni oscurità e illumina la vita e la società.<br>Ora più che mai, continuiamo insieme a diffondere ampiamente i dialoghi per la pace, un compito affidato cinquant’anni fa da Arnold Toynbee alla Soka Gakkai, con la grande speranza che avremmo aperto e mostrato il cammino!<br>Desidero che avanziate con gioia, saggezza e in armonia gli uni con gli altri, 
mentre recitate il ruggito del leone di Nam-myoho-renge-kyo e illuminate le persone intorno a voi con la luce della vostra rivoluzione umana.<br>Sto pregando insieme a mia moglie affinché questo corso possa essere per voi significativo e gioioso, e che voi e le vostre famiglie godiate sempre più di buona salute e prosperità.<br><em>Daisaku Ikeda</em><br>estate 2022
</div>`;
